# Generated by Django 3.2.7 on 2021-10-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='body',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='title',
        ),
        migrations.AddField(
            model_name='blogger',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='blogger',
            name='city',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blogger',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blogger',
            name='district',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blogger',
            name='first_name',
            field=models.CharField(default='kkkk', max_length=200),
        ),
        migrations.AddField(
            model_name='blogger',
            name='last_name',
            field=models.TextField(default='kkkk', max_length=500),
        ),
        migrations.AddField(
            model_name='blogger',
            name='region',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
